# config file: https://golangci-lint.run/usage/configuration/#config-file
# linters: https://golangci-lint.run/usage/linters/

run:
  skip-dirs-use-default: true

linters:
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
  disable:
    - goerr113
    - gomnd
  fast: true

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - scopelint
        - testpackage

linters-settings: {}
